Repository SopkathonTeam3/server, pull requests merged in 2023-05, with the labels that each got.

#3 [FEAT] 엔티티 생성
  src/main/java/com/hackathon/org/common/advice/GlobalExceptionHandler.java
  src/main/java/com/hackathon/org/common/dto/ApiResponseDTO.java
  src/main/java/com/hackathon/org/controller/SampleController.java
  src/main/java/com/hackathon/org/domain/BackgroundImage.java
  src/main/java/com/hackathon/org/domain/Post.java
  src/main/java/com/hackathon/org/domain/Room.java
  src/main/java/com/hackathon/org/domain/User.java
Labels: 😺 승희, ✅ FEAT

#6 feat: 홈 조회 API 구현
  src/main/java/com/hackathon/org/common/status/SuccessStatus.java
  src/main/java/com/hackathon/org/controller/HomeController.java
  src/main/java/com/hackathon/org/controller/SampleController.java
  src/main/java/com/hackathon/org/controller/dto/ReadBackgroundColorDTO.java
  src/main/java/com/hackathon/org/repository/BackgroundColorRepository.java
  src/main/java/com/hackathon/org/service/BackgroundColorService.java
  src/main/java/com/hackathon/org/service/ExampleService.java
Labels: 😇 승하, ✅ FEAT

#7 [FEAT] 전체 조회 기능 구현
  src/main/java/com/hackathon/org/common/advice/GlobalExceptionHandler.java
  src/main/java/com/hackathon/org/common/error/model/BaseException.java
  src/main/java/com/hackathon/org/common/error/model/NotFoundException.java
  src/main/java/com/hackathon/org/common/status/ErrorStatus.java
  src/main/java/com/hackathon/org/controller/PostController.java
  src/main/java/com/hackathon/org/controller/dto/PostListResponseDto.java
  src/main/java/com/hackathon/org/controller/dto/RoomResponseDto.java
  src/main/java/com/hackathon/org/controller/dto/SinglePostResponseDto.java
  src/main/java/com/hackathon/org/controller/dto/UserResponseDto.java
  src/main/java/com/hackathon/org/domain/RemainingCode.java
  src/main/java/com/hackathon/org/domain/Room.java
  src/main/java/com/hackathon/org/domain/User.java
  src/main/java/com/hackathon/org/repository/PostRepository.java
  src/main/java/com/hackathon/org/repository/RoomRepository.java
  src/main/java/com/hackathon/org/service/PostService.java
  src/main/java/com/hackathon/org/service/RoomService.java
  src/main/java/com/hackathon/org/service/UserService.java
  src/main/java/com/hackathon/org/utils/RoomUtil.java
Labels: 😺 승희, ✅ FEAT, 🐛 FIX
